/**
 * Sanitizer Tests
 *
 * Tests to ensure internal data is properly sanitized for merchant API.
 */

import {
  toMerchantCustomer,
  toMerchantCustomerDetail,
  toMerchantSegment,
  sanitizeCustomerObject,
  validateMerchantSafe,
} from '../services/sanitizer';

// Mock internal customer data
const mockInternalCustomer = {
  id: 'cust_123',
  userId: 'user_123',
  email: 'test@example.com',
  phone: '+91 98765 43210',
  firstName: 'John',
  lastName: 'Doe',
  fullName: 'John Doe',
  avatar: 'https://example.com/avatar.jpg',
  demographics: {
    age: 30,
    gender: 'MALE' as const,
    city: 'Mumbai',
    inferredInterests: ['fitness', 'tech'],
    inferredLifestyle: 'urban',
  },
  lifetime: {
    tenureDays: 365,
    totalOrders: 45,
    totalSpend: 125000,
    averageOrderValue: 2778,
    lastOrderDate: new Date('2024-01-15'),
    firstOrderDate: new Date('2023-01-15'),
    predictedLTV: 500000,
    ltvConfidence: 0.85,
    valueTier: 'VIP' as const,
  },
  segments: [
    {
      id: 'seg_1',
      name: 'Champions',
      type: 'RFM' as const,
      description: 'Best customers',
      rules: [],
      logic: 'AND' as const,
      customerCount: 150,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  smartTags: [
    {
      id: 'tag_1',
      name: 'High Spender',
      slug: 'high_spender',
      description: '2x avg order',
      category: 'SPENDING' as const,
      color: '#9333ea',
      customerCount: 245,
      confidence: 0.85,
      isAutoGenerated: true,
      createdAt: new Date(),
    },
    {
      id: 'tag_2',
      name: 'Weekend Visitor',
      slug: 'weekend_visitor',
      description: '60%+ weekend visits',
      category: 'TIMING' as const,
      color: '#3b82f6',
      customerCount: 380,
      confidence: 0.65, // Low confidence - should be filtered
      isAutoGenerated: true,
      createdAt: new Date(),
    },
  ],
  activity: {
    last30Days: { orders: 5, spend: 12500, visits: 8 },
    last90Days: { orders: 12, spend: 35000, visits: 20 },
    last365Days: { orders: 45, spend: 125000, visits: 60 },
    visits: {
      weekday: 60,
      weekend: 40,
      morning: 20,
      afternoon: 30,
      evening: 35,
      night: 15,
    },
    devicePatterns: {
      primaryDevice: 'MOBILE' as const,
      appUsageScore: 0.9,
    },
  },
  engagement: {
    score: 92,
    tier: 'CHAMPION' as const,
    emailEngagementScore: 0.85,
    pushEngagementScore: 0.95,
    channelScores: {
      WHATSAPP: 0.9,
      EMAIL: 0.85,
    },
    emailOptIn: true,
    pushOptIn: true,
    smsOptIn: false,
    engagementFrequency: 'WEEKLY' as const,
    engagementTrend: 'INCREASING' as const,
  },
  predictions: {
    churnRisk: 'LOW' as const,
    churnProbability: 0.05,
    churnDrivers: ['high_satisfaction', 'recent_purchase'],
    nextPurchaseDate: new Date('2024-02-01'),
    nextPurchaseLikelihood: 0.85,
    ltvPrediction: {
      predicted: 500000,
      actual: 125000,
      confidence: 0.85,
      timeframe: '365d' as const,
    },
    productAffinity: [
      { categoryId: 'cat_1', categoryName: 'Pizza', score: 0.9, purchaseFrequency: 10, avgSpend: 800 },
    ],
    preferredChannels: ['WHATSAPP', 'PUSH'],
    crossSellOpportunities: [
      { productId: 'prod_1', productName: 'Garlic Bread', score: 0.8, reason: 'Frequently ordered together' },
    ],
    modelVersion: 'v2.1.0',
    predictionTimestamp: new Date(),
  },
  intentSignals: {
    browsingSignals: {
      viewedProducts: ['prod_1', 'prod_2'],
      viewedCategories: ['pizza', 'beverages'],
      searchQueries: ['pepperoni pizza', 'coke zero'],
      timeOnSite: 300,
      pagesVisited: 12,
      cartAbandonmentRate: 0.2,
    },
    purchaseIntent: {
      score: 85,
      timeframe: 'SHORT_TERM' as const,
      productsOfInterest: ['prod_new_1'],
      priceRange: { min: 500, max: 2000 },
    },
    brandAffinity: [
      { brandName: 'Dominos', affinityScore: 0.9, positiveSignals: 15, negativeSignals: 2 },
    ],
    lifeEvents: [
      { type: 'BIRTHDAY' as const, date: new Date('1994-03-15'), confidence: 0.95 },
    ],
    competitorInterest: [
      { competitorName: 'Dominos', signals: ['visited_website', 'viewed_menu'], frequency: 5 },
    ],
    sentiment: {
      overall: 'POSITIVE' as const,
      score: 0.8,
      keywords: ['love', 'delicious', 'best'],
      lastAnalyzed: new Date(),
    },
    intentScore: 85,
  },
  sources: [
    { source: 'REZ_NOW' as const, externalId: 'user_123', firstSeen: new Date(), lastSync: new Date() },
  ],
  createdAt: new Date('2023-01-15'),
  updatedAt: new Date(),
};

describe('Sanitizer Service', () => {
  describe('toMerchantCustomer', () => {
    it('should transform internal customer to merchant-safe format', () => {
      const merchant = toMerchantCustomer(mockInternalCustomer as any);

      // Should have basic fields
      expect(merchant.id).toBe('cust_123');
      expect(merchant.userId).toBe('user_123');
      expect(merchant.name).toBe('John Doe');
      expect(merchant.phone).toBe('+91 98765 43210');
      expect(merchant.totalOrders).toBe(45);
      expect(merchant.totalSpend).toBe(125000);
      expect(merchant.averageOrderValue).toBe(2778);
    });

    it('should NOT include internal-only fields', () => {
      const merchant = toMerchantCustomer(mockInternalCustomer as any);
      const merchantObj = merchant as unknown as Record<string, unknown>;

      // These should NOT exist
      expect(merchantObj.predictions).toBeUndefined();
      expect(merchantObj.engagement).toBeUndefined();
      expect(merchantObj.intentSignals).toBeUndefined();
      expect(merchantObj.demographics).toBeUndefined();
      expect(merchantObj.activity).toBeUndefined();
    });

    it('should extract segment names only', () => {
      const merchant = toMerchantCustomer(mockInternalCustomer as any);
      expect(merchant.segments).toEqual(['Champions']);
    });
  });

  describe('sanitizeCustomerObject', () => {
    it('should remove forbidden fields', () => {
      const result = sanitizeCustomerObject(mockInternalCustomer as unknown as Record<string, unknown>);

      // Should not contain internal fields
      expect(result.predictions).toBeUndefined();
      expect(result.engagement).toBeUndefined();
      expect(result.intentSignals).toBeUndefined();
      expect(result.demographics).toBeUndefined();
    });

    it('should keep only allowed fields', () => {
      const result = sanitizeCustomerObject(mockInternalCustomer as unknown as Record<string, unknown>);

      // Should keep top-level allowed fields
      expect(result.id).toBeDefined();
      expect(result.fullName).toBeDefined();
      expect(result.phone).toBeDefined();
      expect(result.email).toBeDefined();

      // Should have segments (transformed)
      expect(result.segments).toBeDefined();
      expect(Array.isArray(result.segments)).toBe(true);

      // Should have tags (transformed)
      expect(result.tags).toBeDefined();
      expect(Array.isArray(result.tags)).toBe(true);

      // Should NOT have nested lifetime object
      expect(result.lifetime).toBeUndefined();
    });
  });

  describe('validateMerchantSafe', () => {
    it('should throw error for internal fields', () => {
      const unsafeData = {
        id: '123',
        name: 'Test',
        predictions: { churnRisk: 'HIGH' },
      };

      expect(() => validateMerchantSafe(unsafeData)).toThrow('Internal field');
    });

    it('should throw error for engagement fields', () => {
      const unsafeData = {
        id: '123',
        name: 'Test',
        engagementScore: 95,
      };

      expect(() => validateMerchantSafe(unsafeData)).toThrow('Internal field');
    });

    it('should throw error for intent fields', () => {
      const unsafeData = {
        id: '123',
        name: 'Test',
        intentSignals: { score: 85 },
      };

      expect(() => validateMerchantSafe(unsafeData)).toThrow('Internal field');
    });

    it('should pass for safe merchant data', () => {
      const safeData = {
        id: '123',
        name: 'John Doe',
        phone: '+91 98765 43210',
        totalOrders: 45,
        totalSpend: 125000,
        segments: ['VIP', 'Regular'],
        lastVisit: new Date().toISOString(),
      };

      expect(() => validateMerchantSafe(safeData)).not.toThrow();
    });
  });

  describe('toMerchantSegment', () => {
    it('should transform segment to merchant format', () => {
      const segment = {
        id: 'seg_1',
        name: 'VIP Customers',
        type: 'RFM' as const,
        description: 'High value customers',
        rules: [{ field: 'totalSpend', operator: 'greater_than', value: 50000 }],
        logic: 'AND' as const,
        customerCount: 150,
        totalRevenue: 450000,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      const merchant = toMerchantSegment(segment as any);

      expect(merchant.id).toBe('seg_1');
      expect(merchant.name).toBe('VIP Customers');
      expect(merchant.customerCount).toBe(150);
      expect(merchant.totalRevenue).toBe(450000);
    });
  });
});
