/**
 * ML Feature Store Configuration
 * Defines feature schemas, categories, and metadata for the ReZ ML platform
 */

export enum FeatureCategory {
  USER = 'user',
  MERCHANT = 'merchant',
  TRANSACTION = 'transaction',
  BEHAVIORAL = 'behavioral',
}

export enum FeatureType {
  BOOLEAN = 'boolean',
  INTEGER = 'integer',
  FLOAT = 'float',
  STRING = 'string',
  TIMESTAMP = 'timestamp',
  ARRAY = 'array',
  OBJECT = 'object',
}

export enum FeatureAggregation {
  NONE = 'none',
  SUM = 'sum',
  AVG = 'avg',
  COUNT = 'count',
  MIN = 'min',
  MAX = 'max',
  FIRST = 'first',
  LAST = 'last',
}

export interface FeatureDefinition {
  name: string;
  category: FeatureCategory;
  type: FeatureType;
  description: string;
  aggregation: FeatureAggregation;
  defaultValue: unknown;
  isNullable: boolean;
  entityId: string; // e.g., 'userId', 'merchantId', 'transactionId'
  freshness: string; // e.g., 'realtime', 'hourly', 'daily'
  tags: string[];
}

// User Features Configuration
export const USER_FEATURES: FeatureDefinition[] = [
  {
    name: 'user_age',
    category: FeatureCategory.USER,
    type: FeatureType.INTEGER,
    description: 'User age in years',
    aggregation: FeatureAggregation.NONE,
    defaultValue: null,
    isNullable: true,
    entityId: 'userId',
    freshness: 'realtime',
    tags: ['demographic', 'static'],
  },
  {
    name: 'user_registration_timestamp',
    category: FeatureCategory.USER,
    type: FeatureType.TIMESTAMP,
    description: 'Account creation timestamp',
    aggregation: FeatureAggregation.FIRST,
    defaultValue: null,
    isNullable: false,
    entityId: 'userId',
    freshness: 'realtime',
    tags: ['demographic', 'temporal'],
  },
  {
    name: 'user_verification_status',
    category: FeatureCategory.USER,
    type: FeatureType.BOOLEAN,
    description: 'Whether user has completed verification',
    aggregation: FeatureAggregation.NONE,
    defaultValue: false,
    isNullable: false,
    entityId: 'userId',
    freshness: 'realtime',
    tags: ['kyc', 'trust'],
  },
  {
    name: 'user_risk_score',
    category: FeatureCategory.USER,
    type: FeatureType.FLOAT,
    description: 'User risk score (0-100)',
    aggregation: FeatureAggregation.LAST,
    defaultValue: 50.0,
    isNullable: false,
    entityId: 'userId',
    freshness: 'hourly',
    tags: ['risk', 'fraud'],
  },
  {
    name: 'user_lifetime_value',
    category: FeatureCategory.USER,
    type: FeatureType.FLOAT,
    description: 'Total lifetime value in cents',
    aggregation: FeatureAggregation.SUM,
    defaultValue: 0,
    isNullable: false,
    entityId: 'userId',
    freshness: 'daily',
    tags: ['value', 'business'],
  },
  {
    name: 'user_device_count',
    category: FeatureCategory.USER,
    type: FeatureType.INTEGER,
    description: 'Number of registered devices',
    aggregation: FeatureAggregation.COUNT,
    defaultValue: 0,
    isNullable: false,
    entityId: 'userId',
    freshness: 'realtime',
    tags: ['device', 'security'],
  },
  {
    name: 'user_address_count',
    category: FeatureCategory.USER,
    type: FeatureType.INTEGER,
    description: 'Number of saved addresses',
    aggregation: FeatureAggregation.COUNT,
    defaultValue: 0,
    isNullable: false,
    entityId: 'userId',
    freshness: 'realtime',
    tags: ['profile', 'static'],
  },
  {
    name: 'user_preferred_cuisine_types',
    category: FeatureCategory.USER,
    type: FeatureType.ARRAY,
    description: 'List of preferred cuisine types',
    aggregation: FeatureAggregation.NONE,
    defaultValue: [],
    isNullable: false,
    entityId: 'userId',
    freshness: 'daily',
    tags: ['preference', 'personalization'],
  },
  {
    name: 'user_average_order_value',
    category: FeatureCategory.USER,
    type: FeatureType.FLOAT,
    description: 'Average order value in cents',
    aggregation: FeatureAggregation.AVG,
    defaultValue: 0,
    isNullable: false,
    entityId: 'userId',
    freshness: 'daily',
    tags: ['behavior', 'value'],
  },
  {
    name: 'user_last_order_timestamp',
    category: FeatureCategory.USER,
    type: FeatureType.TIMESTAMP,
    description: 'Last order timestamp',
    aggregation: FeatureAggregation.LAST,
    defaultValue: null,
    isNullable: true,
    entityId: 'userId',
    freshness: 'realtime',
    tags: ['behavior', 'recency'],
  },
];

// Merchant Features Configuration
export const MERCHANT_FEATURES: FeatureDefinition[] = [
  {
    name: 'merchant_rating',
    category: FeatureCategory.MERCHANT,
    type: FeatureType.FLOAT,
    description: 'Average merchant rating (1-5)',
    aggregation: FeatureAggregation.AVG,
    defaultValue: 0,
    isNullable: false,
    entityId: 'merchantId',
    freshness: 'daily',
    tags: ['quality', 'reputation'],
  },
  {
    name: 'merchant_review_count',
    category: FeatureCategory.MERCHANT,
    type: FeatureType.INTEGER,
    description: 'Total number of reviews',
    aggregation: FeatureAggregation.COUNT,
    defaultValue: 0,
    isNullable: false,
    entityId: 'merchantId',
    freshness: 'daily',
    tags: ['quality', 'reputation'],
  },
  {
    name: 'merchant_category',
    category: FeatureCategory.MERCHANT,
    type: FeatureType.STRING,
    description: 'Merchant category classification',
    aggregation: FeatureAggregation.NONE,
    defaultValue: 'general',
    isNullable: false,
    entityId: 'merchantId',
    freshness: 'realtime',
    tags: ['classification', 'static'],
  },
  {
    name: 'merchant_avg_preparation_time',
    category: FeatureCategory.MERCHANT,
    type: FeatureType.INTEGER,
    description: 'Average food preparation time in minutes',
    aggregation: FeatureAggregation.AVG,
    defaultValue: 30,
    isNullable: false,
    entityId: 'merchantId',
    freshness: 'daily',
    tags: ['operations', 'quality'],
  },
  {
    name: 'merchant_min_order_amount',
    category: FeatureCategory.MERCHANT,
    type: FeatureType.INTEGER,
    description: 'Minimum order amount in cents',
    aggregation: FeatureAggregation.NONE,
    defaultValue: 0,
    isNullable: false,
    entityId: 'merchantId',
    freshness: 'realtime',
    tags: ['business', 'static'],
  },
  {
    name: 'merchant_delivery_fee',
    category: FeatureCategory.MERCHANT,
    type: FeatureType.INTEGER,
    description: 'Delivery fee in cents',
    aggregation: FeatureAggregation.NONE,
    defaultValue: 0,
    isNullable: false,
    entityId: 'merchantId',
    freshness: 'realtime',
    tags: ['business', 'pricing'],
  },
  {
    name: 'merchant_daily_volume',
    category: FeatureCategory.MERCHANT,
    type: FeatureType.INTEGER,
    description: 'Average daily order volume',
    aggregation: FeatureAggregation.SUM,
    defaultValue: 0,
    isNullable: false,
    entityId: 'merchantId',
    freshness: 'daily',
    tags: ['volume', 'business'],
  },
  {
    name: 'merchant_fraud_rate',
    category: FeatureCategory.MERCHANT,
    type: FeatureType.FLOAT,
    description: 'Fraud rate percentage (0-100)',
    aggregation: FeatureAggregation.AVG,
    defaultValue: 0,
    isNullable: false,
    entityId: 'merchantId',
    freshness: 'hourly',
    tags: ['risk', 'fraud'],
  },
  {
    name: 'merchant_cancellation_rate',
    category: FeatureCategory.MERCHANT,
    type: FeatureType.FLOAT,
    description: 'Order cancellation rate percentage',
    aggregation: FeatureAggregation.AVG,
    defaultValue: 0,
    isNullable: false,
    entityId: 'merchantId',
    freshness: 'daily',
    tags: ['quality', 'operations'],
  },
  {
    name: 'merchant_accept_rate',
    category: FeatureCategory.MERCHANT,
    type: FeatureType.FLOAT,
    description: 'Order acceptance rate percentage',
    aggregation: FeatureAggregation.AVG,
    defaultValue: 100,
    isNullable: false,
    entityId: 'merchantId',
    freshness: 'daily',
    tags: ['quality', 'operations'],
  },
  {
    name: 'merchant_loyalty_program_enabled',
    category: FeatureCategory.MERCHANT,
    type: FeatureType.BOOLEAN,
    description: 'Whether merchant has loyalty program',
    aggregation: FeatureAggregation.NONE,
    defaultValue: false,
    isNullable: false,
    entityId: 'merchantId',
    freshness: 'realtime',
    tags: ['business', 'static'],
  },
];

// Transaction Features Configuration
export const TRANSACTION_FEATURES: FeatureDefinition[] = [
  {
    name: 'transaction_amount',
    category: FeatureCategory.TRANSACTION,
    type: FeatureType.INTEGER,
    description: 'Transaction amount in cents',
    aggregation: FeatureAggregation.NONE,
    defaultValue: 0,
    isNullable: false,
    entityId: 'transactionId',
    freshness: 'realtime',
    tags: ['transaction', 'amount'],
  },
  {
    name: 'transaction_item_count',
    category: FeatureCategory.TRANSACTION,
    type: FeatureType.INTEGER,
    description: 'Number of items in transaction',
    aggregation: FeatureAggregation.NONE,
    defaultValue: 0,
    isNullable: false,
    entityId: 'transactionId',
    freshness: 'realtime',
    tags: ['transaction', 'volume'],
  },
  {
    name: 'transaction_timestamp',
    category: FeatureCategory.TRANSACTION,
    type: FeatureType.TIMESTAMP,
    description: 'Transaction creation timestamp',
    aggregation: FeatureAggregation.NONE,
    defaultValue: null,
    isNullable: false,
    entityId: 'transactionId',
    freshness: 'realtime',
    tags: ['temporal', 'static'],
  },
  {
    name: 'transaction_payment_method',
    category: FeatureCategory.TRANSACTION,
    type: FeatureType.STRING,
    description: 'Payment method used',
    aggregation: FeatureAggregation.NONE,
    defaultValue: 'unknown',
    isNullable: false,
    entityId: 'transactionId',
    freshness: 'realtime',
    tags: ['payment', 'static'],
  },
  {
    name: 'transaction_promo_code_used',
    category: FeatureCategory.TRANSACTION,
    type: FeatureType.BOOLEAN,
    description: 'Whether promo code was used',
    aggregation: FeatureAggregation.NONE,
    defaultValue: false,
    isNullable: false,
    entityId: 'transactionId',
    freshness: 'realtime',
    tags: ['promotion', 'business'],
  },
  {
    name: 'transaction_tip_percentage',
    category: FeatureCategory.TRANSACTION,
    type: FeatureType.FLOAT,
    description: 'Tip as percentage of subtotal',
    aggregation: FeatureAggregation.NONE,
    defaultValue: 0,
    isNullable: false,
    entityId: 'transactionId',
    freshness: 'realtime',
    tags: ['tip', 'behavior'],
  },
  {
    name: 'transaction_delivery_distance',
    category: FeatureCategory.TRANSACTION,
    type: FeatureType.FLOAT,
    description: 'Delivery distance in kilometers',
    aggregation: FeatureAggregation.NONE,
    defaultValue: 0,
    isNullable: false,
    entityId: 'transactionId',
    freshness: 'realtime',
    tags: ['delivery', 'logistics'],
  },
  {
    name: 'transaction_special_instructions',
    category: FeatureCategory.TRANSACTION,
    type: FeatureType.BOOLEAN,
    description: 'Whether special instructions were provided',
    aggregation: FeatureAggregation.NONE,
    defaultValue: false,
    isNullable: false,
    entityId: 'transactionId',
    freshness: 'realtime',
    tags: ['preference', 'behavior'],
  },
  {
    name: 'transaction_order_type',
    category: FeatureCategory.TRANSACTION,
    type: FeatureType.STRING,
    description: 'Order type: delivery, pickup, dine-in',
    aggregation: FeatureAggregation.NONE,
    defaultValue: 'delivery',
    isNullable: false,
    entityId: 'transactionId',
    freshness: 'realtime',
    tags: ['order', 'classification'],
  },
  {
    name: 'transaction_reorder_flag',
    category: FeatureCategory.TRANSACTION,
    type: FeatureType.BOOLEAN,
    description: 'Whether this is a reorder from previous order',
    aggregation: FeatureAggregation.NONE,
    defaultValue: false,
    isNullable: false,
    entityId: 'transactionId',
    freshness: 'realtime',
    tags: ['behavior', 'loyalty'],
  },
];

// Behavioral Features Configuration
export const BEHAVIORAL_FEATURES: FeatureDefinition[] = [
  {
    name: 'user_order_frequency_7d',
    category: FeatureCategory.BEHAVIORAL,
    type: FeatureType.FLOAT,
    description: 'Average orders per week (7-day rolling)',
    aggregation: FeatureAggregation.AVG,
    defaultValue: 0,
    isNullable: false,
    entityId: 'userId',
    freshness: 'daily',
    tags: ['frequency', 'engagement'],
  },
  {
    name: 'user_order_frequency_30d',
    category: FeatureCategory.BEHAVIORAL,
    type: FeatureType.FLOAT,
    description: 'Average orders per week (30-day rolling)',
    aggregation: FeatureAggregation.AVG,
    defaultValue: 0,
    isNullable: false,
    entityId: 'userId',
    freshness: 'daily',
    tags: ['frequency', 'engagement'],
  },
  {
    name: 'user_avg_session_duration',
    category: FeatureCategory.BEHAVIORAL,
    type: FeatureType.INTEGER,
    description: 'Average session duration in seconds',
    aggregation: FeatureAggregation.AVG,
    defaultValue: 0,
    isNullable: false,
    entityId: 'userId',
    freshness: 'daily',
    tags: ['engagement', 'session'],
  },
  {
    name: 'user_search_to_order_ratio',
    category: FeatureCategory.BEHAVIORAL,
    type: FeatureType.FLOAT,
    description: 'Ratio of searches to orders',
    aggregation: FeatureAggregation.AVG,
    defaultValue: 0,
    isNullable: false,
    entityId: 'userId',
    freshness: 'daily',
    tags: ['conversion', 'intent'],
  },
  {
    name: 'user_price_sensitivity',
    category: FeatureCategory.BEHAVIORAL,
    type: FeatureType.FLOAT,
    description: 'Price sensitivity score (0-100)',
    aggregation: FeatureAggregation.AVG,
    defaultValue: 50,
    isNullable: false,
    entityId: 'userId',
    freshness: 'weekly',
    tags: ['pricing', 'preference'],
  },
  {
    name: 'user_promo_sensitivity',
    category: FeatureCategory.BEHAVIORAL,
    type: FeatureType.FLOAT,
    description: 'Promo code usage tendency (0-100)',
    aggregation: FeatureAggregation.AVG,
    defaultValue: 50,
    isNullable: false,
    entityId: 'userId',
    freshness: 'weekly',
    tags: ['promotion', 'preference'],
  },
  {
    name: 'user_preferred_order_time',
    category: FeatureCategory.BEHAVIORAL,
    type: FeatureType.STRING,
    description: 'Most common order time slot',
    aggregation: FeatureAggregation.NONE,
    defaultValue: 'unknown',
    isNullable: false,
    entityId: 'userId',
    freshness: 'daily',
    tags: ['preference', 'temporal'],
  },
  {
    name: 'user_preferred_payment_method',
    category: FeatureCategory.BEHAVIORAL,
    type: FeatureType.STRING,
    description: 'Most frequently used payment method',
    aggregation: FeatureAggregation.NONE,
    defaultValue: 'unknown',
    isNullable: false,
    entityId: 'userId',
    freshness: 'daily',
    tags: ['preference', 'payment'],
  },
  {
    name: 'user_basket_size_trend',
    category: FeatureCategory.BEHAVIORAL,
    type: FeatureType.FLOAT,
    description: 'Basket size trend direction (-1 to 1)',
    aggregation: FeatureAggregation.NONE,
    defaultValue: 0,
    isNullable: false,
    entityId: 'userId',
    freshness: 'weekly',
    tags: ['trend', 'behavior'],
  },
  {
    name: 'user_churn_probability',
    category: FeatureCategory.BEHAVIORAL,
    type: FeatureType.FLOAT,
    description: 'Predicted churn probability (0-1)',
    aggregation: FeatureAggregation.NONE,
    defaultValue: 0.5,
    isNullable: false,
    entityId: 'userId',
    freshness: 'weekly',
    tags: ['churn', 'ml'],
  },
  {
    name: 'user_engagement_score',
    category: FeatureCategory.BEHAVIORAL,
    type: FeatureType.FLOAT,
    description: 'User engagement score (0-100)',
    aggregation: FeatureAggregation.NONE,
    defaultValue: 50,
    isNullable: false,
    entityId: 'userId',
    freshness: 'daily',
    tags: ['engagement', 'ml'],
  },
  {
    name: 'user_repeat_purchase_rate',
    category: FeatureCategory.BEHAVIORAL,
    type: FeatureType.FLOAT,
    description: 'Repeat purchase rate (0-1)',
    aggregation: FeatureAggregation.AVG,
    defaultValue: 0,
    isNullable: false,
    entityId: 'userId',
    freshness: 'weekly',
    tags: ['loyalty', 'retention'],
  },
];

// Combine all feature definitions
export const ALL_FEATURES: FeatureDefinition[] = [
  ...USER_FEATURES,
  ...MERCHANT_FEATURES,
  ...TRANSACTION_FEATURES,
  ...BEHAVIORAL_FEATURES,
];

// Feature lookup by name
export const FEATURE_BY_NAME = new Map<string, FeatureDefinition>(
  ALL_FEATURES.map((f) => [f.name, f])
);

// Features by category
export const FEATURES_BY_CATEGORY = new Map<FeatureCategory, FeatureDefinition[]>([
  [FeatureCategory.USER, USER_FEATURES],
  [FeatureCategory.MERCHANT, MERCHANT_FEATURES],
  [FeatureCategory.TRANSACTION, TRANSACTION_FEATURES],
  [FeatureCategory.BEHAVIORAL, BEHAVIORAL_FEATURES],
]);

// Entity to features mapping
export const ENTITY_FEATURES = new Map<string, FeatureDefinition[]>([
  ['userId', [...USER_FEATURES, ...BEHAVIORAL_FEATURES]],
  ['merchantId', MERCHANT_FEATURES],
  ['transactionId', TRANSACTION_FEATURES],
]);

// Config validation
export const VALID_FEATURE_TYPES = Object.values(FeatureType);
export const VALID_AGGREGATIONS = Object.values(FeatureAggregation);
export const VALID_CATEGORIES = Object.values(FeatureCategory);
export const VALID_FRESHNESS = ['realtime', 'hourly', 'daily', 'weekly', 'monthly'];

export const FEATURE_STORE_CONFIG = {
  maxFeaturesPerRequest: 100,
  maxEntityValues: 1000,
  featureTTL: 30 * 24 * 60 * 60 * 1000, // 30 days in ms
  cacheTTL: 5 * 60 * 1000, // 5 minutes in ms
  batchSize: 500,
};
